import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { CONFIG_DIR } from "../config.ts";

export const CLOUDFLARED_DIR = join(CONFIG_DIR, "cloudflared");
export const CLOUDFLARED_CONFIG_PATH = join(CLOUDFLARED_DIR, "config.yml");
export const CLOUDFLARED_LOG_PATH = join(CLOUDFLARED_DIR, "cloudflared.log");

export interface TunnelConfigOpts {
  tunnelUuid: string;
  /** Absolute path to the per-tunnel credentials JSON (`~/.cloudflared/<uuid>.json`). */
  credentialsFile: string;
  hostname: string;
  /** Loopback port the tunnel forwards traffic to (vault = 1940). */
  servicePort: number;
}

/**
 * Emit a cloudflared config.yml. The shape is pinned to the documented
 * Named Tunnel + ingress rules schema; we route every request for the
 * configured hostname to the local service port and 404 everything else.
 *
 * Single-hostname ingress today. Multi-service routing (hub at /, vault
 * under /vault/…, etc.) is deferred — the hub/OAuth seam lives on the
 * Tailscale Funnel path and wasn't worth duplicating into the Cloudflare
 * shape before we have a second CF user pushing on it.
 */
/**
 * Double-quote `credentials-file` so a `$HOME` with a space (e.g. macOS
 * "John Doe") doesn't break YAML parsing. Tunnel UUIDs and `http://localhost`
 * URLs don't need quoting by the YAML spec, so only this one path gets it.
 * Backslashes and double-quotes inside the path are escaped.
 */
function yamlQuote(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function renderConfig(opts: TunnelConfigOpts): string {
  return `# Generated by parachute expose public --cloudflare — do not edit by hand.
# Re-running the command regenerates this file.
tunnel: ${opts.tunnelUuid}
credentials-file: ${yamlQuote(opts.credentialsFile)}

ingress:
  - hostname: ${opts.hostname}
    service: http://localhost:${opts.servicePort}
  - service: http_status:404
`;
}

export function writeConfig(
  opts: TunnelConfigOpts,
  configPath: string = CLOUDFLARED_CONFIG_PATH,
): string {
  mkdirSync(dirname(configPath), { recursive: true });
  writeFileSync(configPath, renderConfig(opts));
  return configPath;
}
